version: "4"
services:
  postgres:
    image: postgres:latest
    container_name: inventory-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_service
    ports:
      - "5442:5432" # поменяли внутренний порт, что бы избежать конфликта с order-service-db
    volumes:
      - ./postgres:/var/lib/postgres
      # ! ./postgres => створиться папка на локалій машині, там де заходиться docker-compose
      # ! /var/lib/postgres => папка всередині контейнера
      # ! Щоб усі дані бази зберігалися на хості, навіть якщо контейнер буде видалено або перезапущено.